---
title: "254 Pilot"
author: "Cai Guo"
date: "2/28/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
```

```{r clean data}
d <- read_csv("~/Downloads/Inferring+Identity+from+Language_March+1%2C+2017_01.12.csv")

d_tidy = d %>%
  mutate(index=rownames(d)) %>%
  gather(variable, value, Communicator.F.D:Rude.U.R) %>%
  group_by(index) %>%
  separate(variable, into=c("variable.n", "LIB", "Party")) 

ds = spread(d_tidy, variable.n, value)
ds$Party = as.factor(ds$Party)
ds$Political = as.factor(ds$Political)
ds$LIB = as.factor(ds$LIB)
```

```{r Manipulation Check}
summary(lm(Helpful~LIB, ds))
summary(lm(Rude~LIB, ds))
```

```{r Social Identity Inference}

#Main effects
summary(lm(Communicator~LIB, ds))
summary(lm(Communicator~Party, ds))
summary(lm(Communicator~Political, ds))

#Contrast 1 -- When Favorable LIB, Democrat (communicator), and Democrat (participant) are the defaults
summary(lm(Communicator~LIB*Party*Political, ds))
summary(lm(Communicator~LIB*Party,ds))
summary(lm(Communicator~Party*Political, ds))

#The exact contrasts to test simple effects will be detailed after all data have been collected and the significant interactions have been known.
```

```{r Be Friends}
summary(lm(Friend~LIB, ds))
summary(lm(Friend~Party, ds))
summary(lm(Friend~Political, ds))

summary(lm(Friend~LIB*Party*Political, ds))
summary(lm(Friend~LIB*Party, ds))
summary(lm(Friend~Party*Political, ds))
```